'use client'

import { useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase/client'

const ADMIN_PASSWORD = process.env.NEXT_PUBLIC_ADMIN_PASSWORD || 'buildquote2026'

type Manufacturer = {
  id: string; name: string; slug: string; logo_url: string | null; description: string | null; website_url: string | null
}
type System = {
  id: string; name: string; product_code: string; category: string; subcategory: string | null; sort_order: number
}
type EmbedWidgetSystem = {
  system_id: string; systems: { name: string; product_code: string; manufacturer_id: string }
}
type EmbedWidget = {
  id: string; public_token: string; status: string; created_at: string; embed_widget_systems: EmbedWidgetSystem[]
}
type Supplier = {
  id: string; name: string; slug: string; suburb: string | null; state: string | null; address: string | null
  website_url: string | null; email: string | null; phone: string | null
  manager_name: string | null; it_name: string | null; it_email: string | null
  embed_widgets: EmbedWidget[]
}
type Step = 1 | 2 | 3 | 4

const AU_STATES = ['WA', 'VIC', 'NSW', 'QLD', 'SA', 'TAS', 'ACT', 'NT']
const CATEGORIES = ['Decking', 'Cladding', 'Screening & Fencing']

function slugify(s: string) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
}
function buildEmbedCode(token: string, origin: string) {
  return `<iframe src="${origin}/widget/${token}" width="100%" height="800" frameborder="0" style="border:none;border-radius:12px;"></iframe>`
}

function downloadInstructions(supplierName: string, embedCode: string, previewUrl: string) {
  const html = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>Widget Instructions — ${supplierName}</title>
<style>body{font-family:Arial,sans-serif;max-width:760px;margin:40px auto;padding:0 24px;color:#1f2937;line-height:1.6}h1{font-size:24px;color:#111827;margin-bottom:4px}h2{font-size:18px;color:#111827;margin-top:36px;border-bottom:2px solid #e5e7eb;padding-bottom:8px}h3{font-size:15px;color:#374151;margin-top:20px;margin-bottom:6px}.subtitle{color:#6b7280;font-size:14px;margin-bottom:32px}.code-box{background:#f3f4f6;border:1px solid #e5e7eb;border-radius:8px;padding:16px;font-family:monospace;font-size:13px;word-break:break-all;line-height:1.6;margin:12px 0}.step{background:#f9fafb;border-left:4px solid #2d5a42;padding:14px 18px;border-radius:0 8px 8px 0;margin:12px 0}.tip{background:#fef3c7;border:1px solid #fcd34d;border-radius:8px;padding:12px 16px;font-size:13px;margin:12px 0}footer{margin-top:48px;padding-top:24px;border-top:1px solid #e5e7eb;color:#9ca3af;font-size:12px}</style>
</head><body>
<h1>Product Widget — Setup Instructions</h1>
<p class="subtitle">Prepared for <strong>${supplierName}</strong> by BuildQuote</p>
<h2>Your embed code</h2>
<div class="code-box">${embedCode.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</div>
<p><strong>Preview:</strong> <a href="${previewUrl}" target="_blank">${previewUrl}</a></p>
<div class="tip">💡 Adjust <code>height="800"</code> to fit your layout.</div>
<h2>How to add to your website</h2>
<h3>WordPress</h3><div class="step"><ol><li>Edit the page or post.</li><li>Add a <strong>Custom HTML</strong> block.</li><li>Paste your embed code. Click <strong>Update</strong>.</li></ol></div>
<h3>Squarespace</h3><div class="step"><ol><li>Edit the page. Add a <strong>Code</strong> block.</li><li>Paste your embed code. Save.</li></ol></div>
<h3>Wix</h3><div class="step"><ol><li>Add → Embed → <strong>Embed a Widget</strong>.</li><li>Click <strong>Enter Code</strong> and paste. Save.</li></ol></div>
<h3>Shopify</h3><div class="step"><ol><li>Pages → open page → click <strong>&lt;&gt;</strong>.</li><li>Paste embed code. Save.</li></ol></div>
<h3>Webflow</h3><div class="step"><ol><li>Add an <strong>Embed</strong> element to your page.</li><li>Paste embed code. Save &amp; Close. Publish.</li></ol></div>
<h3>Framer</h3><div class="step"><ol><li>Insert → <strong>Embed</strong>. Paste embed code. Publish.</li></ol></div>
<h3>GoDaddy</h3><div class="step"><ol><li>Add Section → <strong>HTML</strong>. Paste embed code. Save.</li></ol></div>
<h3>Weebly</h3><div class="step"><ol><li>Drag <strong>Embed Code</strong> element. Paste embed code. Save.</li></ol></div>
<h3>Plain HTML</h3><div class="step"><ol><li>Paste inside the <code>&lt;body&gt;</code> tag. Upload.</li></ol></div>
<h2>Need help?</h2><p>Contact BuildQuote: <a href="mailto:hello@buildquote.com.au">hello@buildquote.com.au</a></p>
<footer>Generated by BuildQuote · ${new Date().toLocaleDateString('en-AU', { day: 'numeric', month: 'long', year: 'numeric' })}</footer>
</body></html>`
  const blob = new Blob([html], { type: 'text/html' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url; a.download = `Widget-Instructions-${slugify(supplierName)}.html`; a.click()
  URL.revokeObjectURL(url)
}

function StepBar({ step }: { step: Step }) {
  const steps = ['Supplier details', 'Manufacturer', 'Products', 'Done']
  return (
    <div className="flex items-center gap-0 mb-8">
      {steps.map((label, i) => {
        const n = (i + 1) as Step
        const done = step > n; const active = step === n
        return (
          <div key={n} className="flex items-center flex-1 last:flex-none">
            <div className="flex flex-col items-center gap-1">
              <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold transition-colors ${done ? 'bg-success text-white' : active ? 'bg-brand text-white' : 'bg-ui text-text-faint'}`}>
                {done ? '✓' : n}
              </div>
              <span className={`text-xs whitespace-nowrap ${active ? 'text-text-primary font-medium' : 'text-text-faint'}`}>{label}</span>
            </div>
            {i < steps.length - 1 && <div className={`flex-1 h-px mx-2 mb-4 transition-colors ${done ? 'bg-success' : 'bg-border'}`} />}
          </div>
        )
      })}
    </div>
  )
}

function CopyButton({ text, label = 'Copy' }: { text: string; label?: string }) {
  const [copied, setCopied] = useState(false)
  return (
    <button onClick={() => { navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 2000) }}
      className="text-sm px-4 py-2 bg-brand hover:bg-brand-hover text-white rounded-lg font-medium transition-colors">
      {copied ? 'Copied!' : label}
    </button>
  )
}

function Field({ label, value, placeholder, onChange, type = 'text' }: {
  label: string; value: string; placeholder?: string; onChange: (v: string) => void; type?: string
}) {
  return (
    <div>
      <label className="block text-sm font-medium text-text-secondary mb-1.5">{label}</label>
      <input value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} type={type}
        className="w-full bg-ui border border-border rounded-lg px-3 py-2 text-text-primary placeholder-text-faint text-sm focus:outline-none focus:border-brand" />
    </div>
  )
}

export default function SuppliersTab() {
  const [origin, setOrigin] = useState('')
  const [step, setStep] = useState<Step>(1)
  const [manufacturers, setManufacturers] = useState<Manufacturer[]>([])
  const [systems, setSystems] = useState<System[]>([])
  const [suppliers, setSuppliers] = useState<Supplier[]>([])
  const [loadingData, setLoadingData] = useState(true)

  // Wizard step 1
  const [name, setName] = useState('')
  const [address, setAddress] = useState('')
  const [suburb, setSuburb] = useState('')
  const [stateVal, setStateVal] = useState('')
  const [website, setWebsite] = useState('')
  const [email, setEmail] = useState('')
  const [phone, setPhone] = useState('')
  const [abn, setAbn] = useState('')
  const [portalPassword, setPortalPassword] = useState('')

  // Dynamic contacts
  type ContactRow = { name: string; role: string; email: string; phone: string }
  const emptyContact = (): ContactRow => ({ name: '', role: '', email: '', phone: '' })
  const [contacts, setContacts] = useState<ContactRow[]>([emptyContact()])

  function updateContact(i: number, field: keyof ContactRow, value: string) {
    setContacts(prev => prev.map((c, idx) => idx === i ? { ...c, [field]: value } : c))
  }
  function addContact() { setContacts(prev => [...prev, emptyContact()]) }
  function removeContact(i: number) { setContacts(prev => prev.filter((_, idx) => idx !== i)) }

  // Wizard step 2 + 3
  const [selectedManufacturer, setSelectedManufacturer] = useState<Manufacturer | null>(null)
  const [selectedSystems, setSelectedSystems] = useState<string[]>([])

  // Wizard step 4
  const [newWidget, setNewWidget] = useState<{ token: string; supplierName: string; supplierSlug: string } | null>(null)
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)

  // Edit widget modal
  type EditState = { widgetId: string; supplierName: string; manufacturerId: string }
  const [editState, setEditState] = useState<EditState | null>(null)
  const [editSystems, setEditSystems] = useState<System[]>([])
  const [editSelectedIds, setEditSelectedIds] = useState<string[]>([])
  const [editSaving, setEditSaving] = useState(false)
  const [editError, setEditError] = useState<string | null>(null)

  useEffect(() => {
    setOrigin(window.location.origin)
    loadData()
  }, [])

  async function loadData() {
    setLoadingData(true)
    const [mfRes, suppliersRes] = await Promise.all([
      supabase.from('manufacturers').select('id, name, slug, logo_url, description, website_url').order('name'),
      supabase.from('suppliers').select(`
        id, name, slug, suburb, state, address, website_url, email, phone,
        manager_name, it_name, it_email,
        embed_widgets ( id, public_token, status, created_at,
          embed_widget_systems ( system_id, systems ( name, product_code, manufacturer_id ) ) )
      `).order('name'),
    ])
    if (mfRes.data) setManufacturers(mfRes.data)
    if (suppliersRes.data) setSuppliers(suppliersRes.data as unknown as Supplier[])
    setLoadingData(false)
  }

  async function loadSystems(manufacturerId: string) {
    const { data } = await supabase.from('systems')
      .select('id, name, product_code, category, subcategory, sort_order')
      .eq('manufacturer_id', manufacturerId).order('sort_order')
    if (data) setSystems(data)
  }

  function goStep2() {
    if (!name.trim())           return setError('Business name is required')
    if (!email.trim())          return setError('Login email is required')
    if (!portalPassword.trim()) return setError('Login password is required')
    setError(null); setStep(2)
  }

  function goStep3(mf: Manufacturer) {
    setSelectedManufacturer(mf); setSelectedSystems([]); loadSystems(mf.id); setStep(3)
  }

  async function handleCreate() {
    if (selectedSystems.length === 0) return setError('Select at least one product')
    if (!selectedManufacturer) return
    setSubmitting(true); setError(null)

    const res = await fetch('/api/admin/create-supplier', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'x-admin-password': ADMIN_PASSWORD },
      body: JSON.stringify({
        name, email, login_password: portalPassword,
        address, suburb, state: stateVal, website_url: website,
        phone, abn,
        contacts: contacts.filter(c => c.name.trim()),
        system_ids: selectedSystems,
      }),
    })
    const json = await res.json()
    if (!res.ok) { setError(json.error || 'Failed to create supplier'); setSubmitting(false); return }

    setNewWidget({ token: json.widget.public_token, supplierName: name.trim(), supplierSlug: json.slug })
    setStep(4); setSubmitting(false); loadData()
  }

  function resetWizard() {
    setStep(1)
    setName(''); setAddress(''); setSuburb(''); setStateVal(''); setWebsite('')
    setEmail(''); setPhone(''); setAbn(''); setPortalPassword('')
    setContacts([emptyContact()])
    setSelectedManufacturer(null); setSelectedSystems([]); setNewWidget(null); setError(null)
  }

  async function openEdit(widget: EmbedWidget, supplierName: string) {
    const firstEws = widget.embed_widget_systems[0]
    const manufacturerId = firstEws?.systems?.manufacturer_id
    if (!manufacturerId) return
    const currentIds = widget.embed_widget_systems.map(ews => ews.system_id)
    const { data } = await supabase.from('systems')
      .select('id, name, product_code, category, subcategory, sort_order')
      .eq('manufacturer_id', manufacturerId).order('sort_order')
    if (data) setEditSystems(data)
    setEditSelectedIds(currentIds)
    setEditState({ widgetId: widget.id, supplierName, manufacturerId })
    setEditError(null)
  }

  async function saveEdit() {
    if (!editState || editSelectedIds.length === 0) { setEditError('Select at least one product'); return }
    setEditSaving(true); setEditError(null)
    const res = await fetch('/api/admin/update-widget-systems', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'x-admin-password': ADMIN_PASSWORD },
      body: JSON.stringify({ widgetId: editState.widgetId, systemIds: editSelectedIds }),
    })
    const json = await res.json()
    if (!res.ok) { setEditError(json.error || 'Save failed'); setEditSaving(false); return }
    setEditState(null); setEditSaving(false); loadData()
  }

  const embedCode = newWidget ? buildEmbedCode(newWidget.token, origin) : ''
  const previewUrl = newWidget ? `${origin}/widget/${newWidget.token}` : ''
  const portalUrl  = newWidget ? `${origin}/supplier/${newWidget.supplierSlug}` : ''

  return (
    <div className="space-y-10">

      {/* ── Wizard ── */}
      <section className="bg-surface border border-border rounded-2xl p-8">
        <h2 className="text-xl font-bold text-text-primary mb-6">Add new supplier</h2>
        <StepBar step={step} />

        {/* Step 1 */}
        {step === 1 && (
          <div className="space-y-6">
            <div>
              <p className="text-xs font-semibold text-text-faint uppercase tracking-widest mb-3">Business details</p>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="sm:col-span-2">
                  <label className="block text-sm font-medium text-text-secondary mb-1.5">Business name <span className="text-error">*</span></label>
                  <input value={name} onChange={e => setName(e.target.value)} placeholder="e.g. Bunbury Timber & Hardware"
                    className="w-full bg-ui border border-border rounded-lg px-3 py-2 text-text-primary placeholder-text-faint text-sm focus:outline-none focus:border-brand" />
                </div>
                <div className="sm:col-span-2"><Field label="Street address" value={address} onChange={setAddress} placeholder="123 Main Street" /></div>
                <Field label="Suburb" value={suburb} onChange={setSuburb} placeholder="Bunbury" />
                <div>
                  <label className="block text-sm font-medium text-text-secondary mb-1.5">State</label>
                  <select value={stateVal} onChange={e => setStateVal(e.target.value)}
                    className="w-full bg-ui border border-border rounded-lg px-3 py-2 text-text-primary text-sm focus:outline-none focus:border-brand">
                    <option value="">Select state</option>
                    {AU_STATES.map(s => <option key={s} value={s}>{s}</option>)}
                  </select>
                </div>
                <Field label="Website" value={website} onChange={setWebsite} placeholder="https://example.com.au" type="url" />
                <Field label="Business phone" value={phone} onChange={setPhone} placeholder="08 9999 0000" type="tel" />
                <Field label="ABN / ACN" value={abn} onChange={setAbn} placeholder="12 345 678 901" />
                <Field label="Login email" value={email} onChange={setEmail} placeholder="login@example.com.au" type="email" />
              </div>
            </div>
            <div>
              <p className="text-xs font-semibold text-text-faint uppercase tracking-widest mb-1">Contacts</p>
              <p className="text-xs text-text-faint mb-3">Owners, directors, managers — add as many as needed.</p>
              <div className="space-y-3">
                {contacts.map((c, i) => (
                  <div key={i} className="bg-ui rounded-xl p-4 space-y-3">
                    <div className="flex items-center justify-between">
                      <span className="text-xs font-medium text-text-secondary">Contact {i + 1}</span>
                      {contacts.length > 1 && (
                        <button type="button" onClick={() => removeContact(i)}
                          className="text-xs text-error opacity-60 hover:opacity-100 transition-opacity">
                          Remove
                        </button>
                      )}
                    </div>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                      <input value={c.name} onChange={e => updateContact(i, 'name', e.target.value)}
                        placeholder="Full name"
                        className="w-full bg-surface border border-border rounded-lg px-3 py-2 text-text-primary placeholder-text-faint text-sm focus:outline-none focus:border-brand" />
                      <input value={c.role} onChange={e => updateContact(i, 'role', e.target.value)}
                        placeholder="Role e.g. Owner, Director, Manager"
                        className="w-full bg-surface border border-border rounded-lg px-3 py-2 text-text-primary placeholder-text-faint text-sm focus:outline-none focus:border-brand" />
                      <input value={c.email} onChange={e => updateContact(i, 'email', e.target.value)}
                        placeholder="Email" type="email"
                        className="w-full bg-surface border border-border rounded-lg px-3 py-2 text-text-primary placeholder-text-faint text-sm focus:outline-none focus:border-brand" />
                      <input value={c.phone} onChange={e => updateContact(i, 'phone', e.target.value)}
                        placeholder="Phone" type="tel"
                        className="w-full bg-surface border border-border rounded-lg px-3 py-2 text-text-primary placeholder-text-faint text-sm focus:outline-none focus:border-brand" />
                    </div>
                  </div>
                ))}
                <button type="button" onClick={addContact}
                  className="text-xs text-brand hover:underline font-medium">
                  + Add another contact
                </button>
              </div>
            </div>
            <div>
              <p className="text-xs font-semibold text-text-faint uppercase tracking-widest mb-3">Portal login</p>
              <p className="text-xs text-text-faint mb-3">
                The supplier will use their <strong className="text-text-secondary">Email</strong> (entered above) and this password to log in to the portal.
                Share the password with them securely — they can reset it themselves via "Forgot password".
              </p>
              <label className="block text-sm font-medium text-text-secondary mb-1.5">
                Login password <span className="text-error">*</span>
              </label>
              <input value={portalPassword} onChange={e => setPortalPassword(e.target.value)}
                type="password"
                placeholder="Set an initial password for this supplier"
                className="w-full bg-ui border border-border rounded-lg px-3 py-2 text-text-primary placeholder-text-faint text-sm focus:outline-none focus:border-brand" />
            </div>
            {error && <p className="text-error text-sm">{error}</p>}
            <div className="flex justify-end">
              <button onClick={goStep2} className="px-6 py-2.5 bg-brand hover:bg-brand-hover text-white rounded-lg font-semibold text-sm transition-colors">
                Next: Choose manufacturer →
              </button>
            </div>
          </div>
        )}

        {/* Step 2 */}
        {step === 2 && (
          <div className="space-y-5">
            <p className="text-text-secondary text-sm">Select the manufacturer whose products this supplier stocks.</p>
            {loadingData ? <p className="text-text-faint text-sm">Loading...</p> : (
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                {manufacturers.map(mf => (
                  <button key={mf.id} onClick={() => goStep3(mf)}
                    className="text-left p-5 bg-ui border border-border hover:border-brand rounded-xl transition-colors group">
                    <div className="font-semibold text-text-primary group-hover:text-brand transition-colors">{mf.name}</div>
                    {mf.description && <p className="text-text-faint text-xs mt-1 line-clamp-2">{mf.description}</p>}
                    <div className="mt-3 text-brand text-xs font-medium">Select →</div>
                  </button>
                ))}
              </div>
            )}
            <button onClick={() => setStep(1)} className="text-sm text-text-faint hover:text-text-primary transition-colors">← Back</button>
          </div>
        )}

        {/* Step 3 */}
        {step === 3 && (
          <div className="space-y-5">
            <div className="flex items-center justify-between">
              <p className="text-text-secondary text-sm">Select all <strong className="text-text-primary">{selectedManufacturer?.name}</strong> products this supplier stocks.</p>
              {selectedSystems.length > 0 && <span className="text-brand text-sm font-medium">{selectedSystems.length} selected</span>}
            </div>
            {CATEGORIES.map(cat => {
              const catSystems = systems.filter(s => s.category === cat)
              if (catSystems.length === 0) return null
              return (
                <div key={cat}>
                  <p className="text-xs font-semibold text-text-faint uppercase tracking-widest mb-2">{cat}</p>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                    {catSystems.map(sys => {
                      const isSelected = selectedSystems.includes(sys.id)
                      return (
                        <button key={sys.id} type="button"
                          onClick={() => setSelectedSystems(prev => prev.includes(sys.id) ? prev.filter(s => s !== sys.id) : [...prev, sys.id])}
                          className={`text-left px-3 py-2.5 rounded-lg border text-sm transition-all ${isSelected ? 'bg-brand-subtle border-brand' : 'bg-ui border-border hover:border-brand/60'}`}>
                          <span className="font-mono text-xs text-text-faint block mb-0.5">{sys.product_code}</span>
                          <span className={`font-medium text-sm ${isSelected ? 'text-text-primary' : 'text-text-secondary'}`}>{sys.name}</span>
                          {sys.subcategory && <span className="text-text-faint text-xs block">{sys.subcategory}</span>}
                        </button>
                      )
                    })}
                  </div>
                </div>
              )
            })}
            {error && <p className="text-error text-sm">{error}</p>}
            <div className="flex items-center justify-between pt-2">
              <button onClick={() => setStep(2)} className="text-sm text-text-faint hover:text-text-primary transition-colors">← Back</button>
              <button onClick={handleCreate} disabled={submitting || selectedSystems.length === 0}
                className="px-6 py-2.5 bg-brand hover:bg-brand-hover disabled:opacity-50 disabled:cursor-not-allowed text-white rounded-lg font-semibold text-sm transition-colors">
                {submitting ? 'Creating...' : `Create widget with ${selectedSystems.length || '0'} product${selectedSystems.length !== 1 ? 's' : ''} →`}
              </button>
            </div>
          </div>
        )}

        {/* Step 4 */}
        {step === 4 && newWidget && (
          <div className="space-y-6">
            <div className="text-center py-4">
              <div className="text-4xl mb-3">✓</div>
              <h3 className="text-xl font-bold text-text-primary">Widget created!</h3>
              <p className="text-text-faint text-sm mt-1">Ready for <strong className="text-text-secondary">{newWidget.supplierName}</strong></p>
            </div>
            <div className="space-y-4">
              <div>
                <p className="text-sm font-medium text-text-secondary mb-2">Embed code</p>
                <div className="bg-page rounded-lg p-4 font-mono text-xs text-text-secondary break-all leading-relaxed border border-border">{embedCode}</div>
              </div>
              <div>
                <p className="text-sm font-medium text-text-secondary mb-2">Supplier portal link</p>
                <div className="bg-page rounded-lg p-3 font-mono text-xs text-text-secondary break-all border border-border">{portalUrl}</div>
              </div>
            </div>
            <div className="flex flex-wrap gap-3">
              <CopyButton text={embedCode} label="Copy embed code" />
              <CopyButton text={portalUrl} label="Copy portal link" />
              <button onClick={() => downloadInstructions(newWidget.supplierName, embedCode, previewUrl)}
                className="text-sm px-4 py-2 bg-surface hover:bg-surface-hover border border-border text-text-secondary rounded-lg font-medium transition-colors">
                Download instructions
              </button>
              <a href={previewUrl} target="_blank" rel="noopener noreferrer"
                className="text-sm px-4 py-2 bg-surface hover:bg-surface-hover border border-border text-text-secondary rounded-lg font-medium transition-colors">
                Preview widget ↗
              </a>
              <a href={portalUrl} target="_blank" rel="noopener noreferrer"
                className="text-sm px-4 py-2 bg-surface hover:bg-surface-hover border border-border text-text-secondary rounded-lg font-medium transition-colors">
                Preview portal ↗
              </a>
            </div>
            <div className="pt-2 border-t border-border">
              <button onClick={resetWizard} className="text-sm text-brand hover:underline">+ Add another supplier</button>
            </div>
          </div>
        )}
      </section>

      {/* ── Existing suppliers ── */}
      <section>
        <h2 className="text-lg font-bold text-text-primary mb-5">
          Active suppliers <span className="ml-2 text-sm font-normal text-text-faint">({suppliers.length})</span>
        </h2>
        {loadingData ? <p className="text-text-faint text-sm">Loading...</p>
          : suppliers.length === 0 ? <p className="text-text-faint text-sm">No suppliers yet.</p>
          : (
            <div className="space-y-4">
              {suppliers.map(supplier => (
                <div key={supplier.id} className="bg-surface border border-border rounded-xl p-5">
                  <div className="flex flex-wrap items-baseline gap-x-4 gap-y-1 mb-2">
                    <span className="font-semibold text-text-primary">{supplier.name}</span>
                    {(supplier.suburb || supplier.state) && <span className="text-text-faint text-sm">{[supplier.suburb, supplier.state].filter(Boolean).join(', ')}</span>}
                    {supplier.email && <span className="text-text-faint text-sm">{supplier.email}</span>}
                  </div>
                  <div className="mb-4">
                    <a href={`/supplier/${supplier.slug}`} target="_blank" rel="noopener noreferrer"
                      className="text-brand text-xs hover:underline">View supplier portal ↗</a>
                  </div>
                  {supplier.embed_widgets.map(widget => {
                    const profiles = widget.embed_widget_systems.map(ews => ews.systems)
                    const code = buildEmbedCode(widget.public_token, origin)
                    return (
                      <div key={widget.id} className="bg-ui rounded-lg p-4">
                        <div className="flex flex-wrap gap-2 mb-3">
                          {profiles.map((sys, i) => (
                            <span key={i} className="text-xs bg-brand-subtle text-brand-bright px-2.5 py-1 rounded-full font-medium">
                              {sys.product_code} — {sys.name}
                            </span>
                          ))}
                        </div>
                        <div className="font-mono text-xs text-text-faint bg-page rounded px-3 py-2.5 break-all mb-3 leading-relaxed">{code}</div>
                        <div className="flex flex-wrap gap-3">
                          <CopyButton text={code} label="Copy embed code" />
                          <button onClick={() => openEdit(widget, supplier.name)}
                            className="text-xs px-3 py-1.5 bg-surface hover:bg-surface-hover border border-border text-text-secondary rounded-lg font-medium transition-colors">
                            Edit products
                          </button>
                          <button onClick={() => downloadInstructions(supplier.name, code, `${origin}/widget/${widget.public_token}`)}
                            className="text-xs px-3 py-1.5 bg-surface hover:bg-surface-hover border border-border text-text-secondary rounded-lg font-medium transition-colors">
                            Download instructions
                          </button>
                          <a href={`/widget/${widget.public_token}`} target="_blank" rel="noopener noreferrer"
                            className="text-xs px-3 py-1.5 bg-surface hover:bg-surface-hover border border-border text-text-secondary rounded-lg font-medium transition-colors">
                            Preview ↗
                          </a>
                        </div>
                      </div>
                    )
                  })}
                </div>
              ))}
            </div>
          )}
      </section>

      {/* ── Edit products modal ── */}
      {editState && (
        <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center p-4"
          style={{ background: 'rgba(0,0,0,0.55)' }}
          onClick={e => { if (e.target === e.currentTarget) setEditState(null) }}>
          <div className="bg-surface border border-border rounded-2xl w-full max-w-2xl max-h-[85vh] flex flex-col shadow-2xl">
            <div className="flex items-center justify-between px-6 py-4 border-b border-border">
              <div>
                <h3 className="font-bold text-text-primary">Edit products</h3>
                <p className="text-xs text-text-faint mt-0.5">{editState.supplierName}</p>
              </div>
              <button onClick={() => setEditState(null)} className="text-text-faint hover:text-text-primary text-xl leading-none px-1">×</button>
            </div>
            <div className="overflow-y-auto flex-1 px-6 py-5 space-y-5">
              {editSelectedIds.length > 0 && <p className="text-brand text-sm font-medium">{editSelectedIds.length} selected</p>}
              {CATEGORIES.map(cat => {
                const catSystems = editSystems.filter(s => s.category === cat)
                if (catSystems.length === 0) return null
                return (
                  <div key={cat}>
                    <p className="text-xs font-semibold text-text-faint uppercase tracking-widest mb-2">{cat}</p>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                      {catSystems.map(sys => {
                        const isSelected = editSelectedIds.includes(sys.id)
                        return (
                          <button key={sys.id} type="button"
                            onClick={() => setEditSelectedIds(prev => prev.includes(sys.id) ? prev.filter(id => id !== sys.id) : [...prev, sys.id])}
                            className={`text-left px-3 py-2.5 rounded-lg border text-sm transition-all ${isSelected ? 'bg-brand-subtle border-brand' : 'bg-ui border-border hover:border-brand/60'}`}>
                            <span className="font-mono text-xs text-text-faint block mb-0.5">{sys.product_code}</span>
                            <span className={`font-medium text-sm ${isSelected ? 'text-text-primary' : 'text-text-secondary'}`}>{sys.name}</span>
                            {sys.subcategory && <span className="text-text-faint text-xs block">{sys.subcategory}</span>}
                          </button>
                        )
                      })}
                    </div>
                  </div>
                )
              })}
              {editError && <p className="text-error text-sm">{editError}</p>}
            </div>
            <div className="px-6 py-4 border-t border-border flex items-center justify-between gap-3">
              <button onClick={() => setEditState(null)} className="text-sm text-text-faint hover:text-text-primary transition-colors">Cancel</button>
              <button onClick={saveEdit} disabled={editSaving || editSelectedIds.length === 0}
                className="px-6 py-2.5 bg-brand hover:bg-brand-hover disabled:opacity-50 disabled:cursor-not-allowed text-white rounded-lg font-semibold text-sm transition-colors">
                {editSaving ? 'Saving...' : `Save ${editSelectedIds.length} product${editSelectedIds.length !== 1 ? 's' : ''}`}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
