'use client'

import { useState } from 'react'
import {
  SupplierData, Manufacturer, WidgetRecord, CATEGORIES,
  buildEmbedCode, slugify, formatDate,
} from './shared'

function downloadInstructions(supplierName: string, embedCode: string, previewUrl: string) {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Widget Setup Instructions — ${supplierName}</title>
<style>
  body { font-family: Arial, sans-serif; max-width: 760px; margin: 40px auto; padding: 0 24px; color: #1f2937; line-height: 1.6; }
  h1 { font-size: 24px; color: #111827; margin-bottom: 4px; }
  h2 { font-size: 18px; color: #111827; margin-top: 36px; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px; }
  h3 { font-size: 15px; color: #374151; margin-top: 20px; margin-bottom: 6px; }
  .subtitle { color: #6b7280; font-size: 14px; margin-bottom: 32px; }
  .code-box { background: #f3f4f6; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; font-family: monospace; font-size: 13px; word-break: break-all; line-height: 1.6; margin: 12px 0; }
  .step { background: #f9fafb; border-left: 4px solid #185D7A; padding: 14px 18px; border-radius: 0 8px 8px 0; margin: 12px 0; }
  .tip { background: #fef3c7; border: 1px solid #fcd34d; border-radius: 8px; padding: 12px 16px; font-size: 13px; margin: 12px 0; }
  footer { margin-top: 48px; padding-top: 24px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 12px; }
</style>
</head>
<body>
<h1>Product Widget — Setup Instructions</h1>
<p class="subtitle">Prepared for <strong>${supplierName}</strong> by BuildQuote</p>
<h2>Your embed code</h2>
<div class="code-box">${embedCode.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</div>
<p><strong>Preview:</strong> <a href="${previewUrl}" target="_blank">${previewUrl}</a></p>
<div class="tip">💡 Adjust <code>height="800"</code> to fit your layout.</div>
<h2>How to add to your website</h2>
<h3>WordPress</h3>
<div class="step"><ol><li>Edit the page or post.</li><li>Add a <strong>Custom HTML</strong> block.</li><li>Paste your embed code. Click <strong>Update</strong>.</li></ol></div>
<h3>Squarespace</h3>
<div class="step"><ol><li>Edit the page. Add a <strong>Code</strong> block.</li><li>Paste your embed code. Save.</li></ol></div>
<h3>Wix</h3>
<div class="step"><ol><li>Add → Embed → <strong>Embed a Widget</strong>.</li><li>Click <strong>Enter Code</strong> and paste. Save.</li></ol></div>
<h3>Shopify</h3>
<div class="step"><ol><li>Pages → open page → click <strong>&lt;&gt;</strong>.</li><li>Paste embed code. Save.</li></ol></div>
<h3>Webflow</h3>
<div class="step"><ol><li>Add an <strong>Embed</strong> element to your page.</li><li>Paste embed code. Save &amp; Close. Publish.</li></ol></div>
<h3>Framer</h3>
<div class="step"><ol><li>Insert → <strong>Embed</strong>. Paste embed code. Publish.</li></ol></div>
<h3>GoDaddy</h3>
<div class="step"><ol><li>Add Section → <strong>HTML</strong>. Paste embed code. Save.</li></ol></div>
<h3>Weebly</h3>
<div class="step"><ol><li>Drag <strong>Embed Code</strong> element. Paste embed code. Save.</li></ol></div>
<h3>Plain HTML</h3>
<div class="step"><ol><li>Paste inside the <code>&lt;body&gt;</code> tag. Upload.</li></ol></div>
<h2>Need help?</h2>
<p>Contact BuildQuote: <a href="mailto:hello@buildquote.com.au">hello@buildquote.com.au</a> · <a href="https://buildquote.com.au">buildquote.com.au</a></p>
<footer>Generated by BuildQuote · ${new Date().toLocaleDateString('en-AU', { day: 'numeric', month: 'long', year: 'numeric' })}</footer>
</body></html>`
  const blob = new Blob([html], { type: 'text/html' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url; a.download = `Widget-Instructions-${slugify(supplierName)}.html`; a.click()
  URL.revokeObjectURL(url)
}

type EditSystem = {
  id: string; name: string; product_code: string
  category: string; subcategory: string | null; sort_order: number
}

// ── Manufacturer logo / initial ───────────────────────────────────────────────

function MfLogo({ manufacturer, size = 52 }: { manufacturer: Manufacturer | undefined; size?: number }) {
  const initial = manufacturer?.name?.[0]?.toUpperCase() ?? '?'
  return (
    <div style={{
      width: `${size}px`, height: `${size}px`, borderRadius: '10px', flexShrink: 0,
      background: manufacturer?.logo_url ? 'rgba(255,255,255,0.08)' : '#185D7A',
      border: '1.5px solid rgba(255,255,255,0.1)',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      overflow: 'hidden',
    }}>
      {manufacturer?.logo_url ? (
        <img src={manufacturer.logo_url} alt={manufacturer.name}
          style={{ width: '100%', height: '100%', objectFit: 'contain', padding: '7px' }} />
      ) : (
        <span style={{ fontSize: `${Math.round(size * 0.38)}px`, fontWeight: 800, color: '#fff' }}>
          {initial}
        </span>
      )}
    </div>
  )
}

// ── Widget card ───────────────────────────────────────────────────────────────

function WidgetCard({
  widget, manufacturer, supplier, origin, onEdit, onDownload,
}: {
  widget: WidgetRecord
  manufacturer: Manufacturer | undefined
  supplier: SupplierData
  origin: string
  onEdit: (w: WidgetRecord) => void
  onDownload: (w: WidgetRecord) => void
}) {
  const [copied,   setCopied]   = useState(false)
  const [showCode, setShowCode] = useState(false)

  const profiles   = widget.embed_widget_systems.map(ews => ews.systems)
  const code       = buildEmbedCode(widget.public_token, origin)
  const previewUrl = `${origin}/widget/${widget.public_token}`
  const isActive   = widget.status === 'active'

  function copyCode() {
    navigator.clipboard.writeText(code)
    setCopied(true)
    setTimeout(() => setCopied(false), 2500)
  }

  return (
    <div style={{
      background: 'rgba(255,255,255,0.04)',
      border: '1px solid rgba(255,255,255,0.1)',
      borderRadius: '16px', overflow: 'hidden',
      display: 'flex', flexDirection: 'column',
    }}>

      {/* ── Brand header ── */}
      <div style={{ padding: '18px 18px 14px', display: 'flex', alignItems: 'flex-start', gap: '12px' }}>
        <MfLogo manufacturer={manufacturer} />
        <div style={{ flex: 1 }}>
          <p style={{
            margin: 0, fontSize: '15px', fontWeight: 700,
            color: '#e8f4f8', lineHeight: 1.3,
            wordBreak: 'break-word',
          }}>
            {manufacturer?.name ?? 'Unknown manufacturer'}
          </p>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginTop: '5px', flexWrap: 'wrap' }}>
            <span style={{
              fontSize: '11px', fontWeight: 600, padding: '2px 8px', borderRadius: '20px',
              background: isActive ? 'rgba(74,222,128,0.15)' : 'rgba(248,113,113,0.15)',
              color: isActive ? '#4ade80' : '#f87171',
            }}>
              ● {widget.status}
            </span>
            <span style={{ fontSize: '12px', color: '#6b8ea0' }}>
              {profiles.length} of {manufacturer?.systems.length ?? profiles.length} products selected
            </span>
          </div>
        </div>
      </div>

      {/* ── Product list ── */}
      <div style={{ padding: '0 18px 16px', flex: 1 }}>
        <div style={{ borderTop: '1px solid rgba(255,255,255,0.07)', paddingTop: '12px' }}>
          {profiles.map((sys, i) => (
            <div key={i} style={{
              padding: '5px 0',
              borderBottom: i < profiles.length - 1 ? '1px solid rgba(255,255,255,0.05)' : 'none',
              fontSize: '13px', color: '#90b8cc', lineHeight: 1.4,
              wordBreak: 'break-word',
            }}>
              {sys.name}
            </div>
          ))}
        </div>
      </div>

      {/* ── Primary: copy embed code ── */}
      <div style={{ padding: '0 18px 8px' }}>
        <button
          onClick={copyCode}
          style={{
            width: '100%', padding: '13px 16px',
            background: copied ? '#166534' : '#185D7A',
            color: '#fff', border: 'none', borderRadius: '10px',
            fontWeight: 700, fontSize: '14px', cursor: 'pointer',
            transition: 'background 0.2s', letterSpacing: '0.01em',
          }}
        >
          {copied ? '✓ Copied to clipboard!' : 'Copy embed code'}
        </button>
      </div>

      {/* ── Secondary: preview ── */}
      <div style={{ padding: '0 18px 12px' }}>
        <a
          href={previewUrl} target="_blank" rel="noopener noreferrer"
          style={{
            display: 'block', width: '100%', padding: '11px 16px',
            background: 'transparent',
            border: '1.5px solid rgba(144,184,204,0.35)',
            color: '#90c8de', textDecoration: 'none',
            fontWeight: 600, fontSize: '13px',
            borderRadius: '10px', textAlign: 'center',
            boxSizing: 'border-box',
          }}
        >
          Preview widget ↗
        </a>
      </div>

      {/* ── Tertiary actions ── */}
      <div style={{
        padding: '10px 18px 14px',
        borderTop: '1px solid rgba(255,255,255,0.06)',
        display: 'flex', gap: '16px', flexWrap: 'wrap', alignItems: 'center',
      }}>
        <button onClick={() => onEdit(widget)}
          style={{ fontSize: '12px', color: '#6b8ea0', background: 'none', border: 'none', cursor: 'pointer', fontWeight: 500, padding: 0 }}>
          Edit products
        </button>
        <button onClick={() => onDownload(widget)}
          style={{ fontSize: '12px', color: '#6b8ea0', background: 'none', border: 'none', cursor: 'pointer', fontWeight: 500, padding: 0 }}>
          Setup guide ↓
        </button>
        <button
          onClick={() => setShowCode(v => !v)}
          style={{ fontSize: '12px', color: '#4a6b7a', background: 'none', border: 'none', cursor: 'pointer', padding: 0, marginLeft: 'auto' }}>
          {showCode ? 'Hide code ▲' : 'Show code ▼'}
        </button>
      </div>

      {/* ── Collapsible embed code ── */}
      {showCode && (
        <div style={{
          margin: '0 18px 16px',
          background: 'rgba(0,0,0,0.3)', borderRadius: '8px',
          padding: '10px 12px', fontFamily: 'monospace', fontSize: '11px',
          color: '#6b8899', wordBreak: 'break-all', lineHeight: 1.6,
          border: '1px solid rgba(255,255,255,0.07)',
        }}>
          {code}
        </div>
      )}
    </div>
  )
}

// ── Main component ────────────────────────────────────────────────────────────

export function ProductsTab({
  supplier, manufacturers, accessToken, slug, origin, onReload,
}: {
  supplier: SupplierData
  manufacturers: Manufacturer[]
  accessToken: string
  slug: string
  origin: string
  onReload: () => void
}) {
  const [addWidgetMode, setAddWidgetMode]         = useState(false)
  const [selectedMf, setSelectedMf]               = useState<Manufacturer | null>(null)
  const [selectedSystems, setSelectedSystems]     = useState<string[]>([])
  const [creatingWidget, setCreatingWidget]       = useState(false)
  const [createWidgetError, setCreateWidgetError] = useState<string | null>(null)

  const [editState, setEditState]             = useState<{ widgetId: string; manufacturerId: string } | null>(null)
  const [editSystems, setEditSystems]         = useState<EditSystem[]>([])
  const [editSelectedIds, setEditSelectedIds] = useState<string[]>([])
  const [editSaving, setEditSaving]           = useState(false)
  const [editError, setEditError]             = useState<string | null>(null)

  const coveredMfIds = new Set(
    supplier.embed_widgets.flatMap(w =>
      w.embed_widget_systems.map(ews => ews.systems.manufacturer_id)
    )
  )

  async function handleCreateWidget() {
    if (!selectedMf || selectedSystems.length === 0) return
    setCreatingWidget(true); setCreateWidgetError(null)
    const res = await fetch('/api/supplier/create-widget', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${accessToken}` },
      body: JSON.stringify({ supplierSlug: slug, systemIds: selectedSystems }),
    })
    const json = await res.json()
    if (!res.ok) { setCreateWidgetError(json.error || 'Failed'); setCreatingWidget(false); return }
    setAddWidgetMode(false); setSelectedMf(null); setSelectedSystems([])
    setCreatingWidget(false); onReload()
  }

  function openEdit(widget: WidgetRecord) {
    const mfId = widget.embed_widget_systems[0]?.systems?.manufacturer_id
    if (!mfId) return
    const mf = manufacturers.find(m => m.id === mfId)
    setEditSystems((mf?.systems ?? []).slice().sort((a, b) => a.sort_order - b.sort_order))
    setEditSelectedIds(widget.embed_widget_systems.map(ews => ews.system_id))
    setEditState({ widgetId: widget.id, manufacturerId: mfId })
    setEditError(null)
  }

  function handleDownload(widget: WidgetRecord) {
    const code = buildEmbedCode(widget.public_token, origin)
    const previewUrl = `${origin}/widget/${widget.public_token}`
    downloadInstructions(supplier.name, code, previewUrl)
  }

  async function saveEdit() {
    if (!editState || editSelectedIds.length === 0) { setEditError('Select at least one product'); return }
    setEditSaving(true); setEditError(null)
    const res = await fetch('/api/supplier/update-widget-systems', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${accessToken}` },
      body: JSON.stringify({ widgetId: editState.widgetId, systemIds: editSelectedIds, supplierSlug: slug }),
    })
    const json = await res.json()
    if (!res.ok) { setEditError(json.error || 'Save failed'); setEditSaving(false); return }
    setEditState(null); setEditSaving(false); onReload()
  }

  const sortedWidgets = supplier.embed_widgets
    .slice()
    .sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime())

  return (
    <>
      {/* ── Page header ──────────────────────────────────────────────────── */}
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: '16px', marginBottom: '20px', flexWrap: 'wrap' }}>
        <div>
          <h2 style={{ margin: 0, fontSize: '16px', fontWeight: 700, color: '#e8f4f8' }}>
            Product widgets
          </h2>
          <p style={{ margin: '4px 0 0', fontSize: '13px', color: '#6b8ea0', lineHeight: 1.5 }}>
            {sortedWidgets.length > 0
              ? 'Copy an embed code and paste it on your website — your product range appears automatically.'
              : 'Add the manufacturers you stock. Each gets an embeddable product widget for your website, free.'}
          </p>
        </div>
        {!addWidgetMode && sortedWidgets.length > 0 && (
          <button
            onClick={() => { setAddWidgetMode(true); setSelectedMf(null); setSelectedSystems([]) }}
            style={{
              padding: '10px 18px', background: '#185D7A', color: '#fff',
              border: 'none', borderRadius: '10px', fontWeight: 600, fontSize: '13px',
              cursor: 'pointer', flexShrink: 0, display: 'flex', alignItems: 'center', gap: '6px',
            }}
          >
            <span style={{ fontSize: '16px', lineHeight: 1 }}>+</span>
            Add manufacturer
          </button>
        )}
      </div>

      {/* ── How it works — shown only when widgets exist ──────────────────── */}
      {sortedWidgets.length > 0 && !addWidgetMode && (
        <div style={{
          display: 'flex', gap: '0', marginBottom: '24px',
          background: 'rgba(24,93,122,0.12)', border: '1px solid rgba(24,93,122,0.25)',
          borderRadius: '12px', overflow: 'hidden',
        }}>
          {[
            { n: '1', text: 'Find the manufacturer card' },
            { n: '2', text: 'Click Copy embed code' },
            { n: '3', text: 'Paste it on your website' },
          ].map((step, i, arr) => (
            <div key={i} style={{
              flex: 1, padding: '12px 14px', textAlign: 'center',
              borderRight: i < arr.length - 1 ? '1px solid rgba(24,93,122,0.25)' : 'none',
            }}>
              <div style={{ fontSize: '11px', fontWeight: 700, color: '#185D7A', marginBottom: '3px' }}>
                STEP {step.n}
              </div>
              <div style={{ fontSize: '12px', color: '#8ab8cc', lineHeight: 1.4 }}>
                {step.text}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* ── Add widget panel ─────────────────────────────────────────────── */}
      {addWidgetMode && (
        <div className="bg-surface border border-border rounded-xl p-6 mb-6 space-y-5">
          {!selectedMf ? (
            <>
              <div className="flex items-center justify-between">
                <p className="text-sm font-semibold text-text-primary">Select a manufacturer</p>
                <button onClick={() => setAddWidgetMode(false)} className="text-xs text-text-faint hover:text-text-primary">Cancel</button>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                {manufacturers.map(mf => {
                  const hasWidget = coveredMfIds.has(mf.id)
                  return (
                    <button key={mf.id}
                      onClick={() => { if (!hasWidget) { setSelectedMf(mf); setSelectedSystems([]) } }}
                      disabled={hasWidget}
                      className={`text-left p-4 rounded-xl border transition-colors flex items-start gap-3 ${hasWidget ? 'opacity-50 cursor-not-allowed border-border bg-ui' : 'border-border hover:border-brand bg-ui'}`}>
                      <MfLogo manufacturer={mf} size={40} />
                      <div className="flex-1 min-w-0">
                        <p className="font-semibold text-text-primary text-sm" style={{ wordBreak: 'break-word' }}>{mf.name}</p>
                        {mf.description && <p className="text-text-faint text-xs mt-0.5 line-clamp-1">{mf.description}</p>}
                        {hasWidget
                          ? <span className="text-xs text-brand-bright mt-1 block">✓ Widget active</span>
                          : <span className="text-xs text-brand mt-1 block">{mf.systems.length} products →</span>
                        }
                      </div>
                    </button>
                  )
                })}
              </div>
            </>
          ) : (
            <>
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm font-semibold text-text-primary">{selectedMf.name}</p>
                  <p className="text-text-faint text-xs mt-0.5">Select the products your business stocks</p>
                </div>
                <div className="flex gap-3 items-center">
                  {selectedSystems.length > 0 && <span className="text-brand text-sm font-medium">{selectedSystems.length} selected</span>}
                  <button onClick={() => setSelectedMf(null)} className="text-xs text-text-faint hover:text-text-primary">← Back</button>
                </div>
              </div>

              {[...new Set(selectedMf.systems.map(s => s.category))].sort().map(cat => {
                const catSystems = selectedMf.systems.filter(s => s.category === cat).sort((a, b) => a.sort_order - b.sort_order)
                if (catSystems.length === 0) return null
                return (
                  <div key={cat}>
                    <p className="text-xs font-semibold text-text-faint uppercase tracking-widest mb-2">{cat}</p>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                      {catSystems.map(sys => {
                        const sel = selectedSystems.includes(sys.id)
                        return (
                          <button key={sys.id} type="button"
                            onClick={() => setSelectedSystems(prev => prev.includes(sys.id) ? prev.filter(id => id !== sys.id) : [...prev, sys.id])}
                            style={{
                              position: 'relative',
                              textAlign: 'left', padding: '10px 12px',
                              borderRadius: '10px',
                              border: sel ? '2px solid #185D7A' : '2px solid rgba(255,255,255,0.1)',
                              background: sel ? 'rgba(24,93,122,0.28)' : 'rgba(255,255,255,0.04)',
                              cursor: 'pointer', transition: 'all 0.15s',
                              boxShadow: sel ? '0 0 0 1px rgba(24,93,122,0.4) inset' : 'none',
                            }}>
                            {/* Tick badge */}
                            <span style={{
                              position: 'absolute', top: '8px', right: '8px',
                              width: '20px', height: '20px', borderRadius: '50%',
                              background: sel ? '#185D7A' : 'rgba(255,255,255,0.08)',
                              border: sel ? '2px solid #2596be' : '2px solid rgba(255,255,255,0.15)',
                              display: 'flex', alignItems: 'center', justifyContent: 'center',
                              fontSize: '11px', color: '#fff', fontWeight: 800,
                              transition: 'all 0.15s', flexShrink: 0,
                            }}>
                              {sel ? '✓' : ''}
                            </span>
                            <span style={{ fontFamily: 'monospace', fontSize: '11px', color: sel ? '#7dd3ee' : '#6b8ea0', display: 'block', marginBottom: '2px' }}>{sys.product_code}</span>
                            <span style={{ fontWeight: 600, fontSize: '13px', color: sel ? '#e8f4f8' : '#8ab8cc', wordBreak: 'break-word', display: 'block', paddingRight: '24px' }}>{sys.name}</span>
                            {sys.subcategory && <span style={{ fontSize: '11px', color: sel ? '#90c8de' : '#4a6b7a', display: 'block', marginTop: '2px' }}>{sys.subcategory}</span>}
                          </button>
                        )
                      })}
                    </div>
                  </div>
                )
              })}

              {createWidgetError && <p className="text-error text-sm">{createWidgetError}</p>}

              <div className="flex items-center gap-3 pt-2 border-t border-border-subtle">
                <button onClick={handleCreateWidget}
                  disabled={creatingWidget || selectedSystems.length === 0}
                  className="px-5 py-2.5 bg-brand hover:bg-brand-hover disabled:opacity-50 text-white rounded-lg font-semibold text-sm transition-colors">
                  {creatingWidget ? 'Creating widget…' : `Create widget — ${selectedSystems.length || 0} product${selectedSystems.length !== 1 ? 's' : ''} →`}
                </button>
                <button onClick={() => setAddWidgetMode(false)} className="text-sm text-text-faint hover:text-text-primary">Cancel</button>
              </div>
            </>
          )}
        </div>
      )}

      {/* ── Empty state ───────────────────────────────────────────────────── */}
      {sortedWidgets.length === 0 && !addWidgetMode && (
        <div style={{
          border: '2px dashed rgba(255,255,255,0.1)',
          borderRadius: '20px', padding: '52px 24px', textAlign: 'center',
        }}>
          <div style={{
            width: '64px', height: '64px', borderRadius: '16px',
            background: 'rgba(24,93,122,0.2)', margin: '0 auto 20px',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            fontSize: '28px',
          }}>
            🏗️
          </div>
          <p style={{ fontWeight: 700, color: '#e8f4f8', fontSize: '16px', margin: '0 0 8px' }}>
            Add your first product widget
          </p>
          <p style={{ color: '#6b8ea0', fontSize: '13px', maxWidth: '340px', margin: '0 auto 24px', lineHeight: 1.6 }}>
            Pick the manufacturers you stock. Each gets a beautiful, embeddable product catalogue for your website — completely free.
          </p>
          <button
            onClick={() => { setAddWidgetMode(true); setSelectedMf(null); setSelectedSystems([]) }}
            style={{
              padding: '13px 24px', background: '#185D7A', color: '#fff',
              border: 'none', borderRadius: '12px', fontWeight: 700, fontSize: '14px',
              cursor: 'pointer',
            }}
          >
            Browse manufacturers & product lines →
          </button>
        </div>
      )}

      {/* ── Widget grid ───────────────────────────────────────────────────── */}
      {sortedWidgets.length > 0 && (
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
          gap: '16px',
        }}>
          {sortedWidgets.map(widget => {
            const mfId = widget.embed_widget_systems[0]?.systems?.manufacturer_id
            const manufacturer = manufacturers.find(m => m.id === mfId)
            return (
              <WidgetCard
                key={widget.id}
                widget={widget}
                manufacturer={manufacturer}
                supplier={supplier}
                origin={origin}
                onEdit={openEdit}
                onDownload={handleDownload}
              />
            )
          })}
        </div>
      )}

      {/* ── Edit products modal ───────────────────────────────────────────── */}
      {editState && (
        <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center p-4"
          style={{ background: 'rgba(0,0,0,0.55)' }}
          onClick={e => { if (e.target === e.currentTarget) setEditState(null) }}>
          <div className="bg-surface border border-border rounded-2xl w-full max-w-2xl max-h-[85vh] flex flex-col shadow-2xl">
            <div className="flex items-center justify-between px-6 py-4 border-b border-border">
              <div>
                <h3 className="font-bold text-text-primary">Edit products</h3>
                <p className="text-xs text-text-faint mt-0.5">Toggle the products your business stocks</p>
              </div>
              <button onClick={() => setEditState(null)} className="text-text-faint hover:text-text-primary text-xl leading-none px-1">×</button>
            </div>
            <div className="overflow-y-auto flex-1 px-6 py-5 space-y-5">
              {editSelectedIds.length > 0 && (
                <p className="text-brand text-sm font-medium">{editSelectedIds.length} selected</p>
              )}
              {[...new Set(editSystems.map(s => s.category))].sort().map(cat => {
                const catSystems = editSystems.filter(s => s.category === cat)
                if (catSystems.length === 0) return null
                return (
                  <div key={cat}>
                    <p className="text-xs font-semibold text-text-faint uppercase tracking-widest mb-2">{cat}</p>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                      {catSystems.map(sys => {
                        const isSelected = editSelectedIds.includes(sys.id)
                        return (
                          <button key={sys.id} type="button"
                            onClick={() => setEditSelectedIds(prev => prev.includes(sys.id) ? prev.filter(id => id !== sys.id) : [...prev, sys.id])}
                            style={{
                              position: 'relative',
                              textAlign: 'left', padding: '10px 12px',
                              borderRadius: '10px',
                              border: isSelected ? '2px solid #185D7A' : '2px solid rgba(255,255,255,0.1)',
                              background: isSelected ? 'rgba(24,93,122,0.28)' : 'rgba(255,255,255,0.04)',
                              cursor: 'pointer', transition: 'all 0.15s',
                              boxShadow: isSelected ? '0 0 0 1px rgba(24,93,122,0.4) inset' : 'none',
                            }}>
                            {/* Tick badge */}
                            <span style={{
                              position: 'absolute', top: '8px', right: '8px',
                              width: '20px', height: '20px', borderRadius: '50%',
                              background: isSelected ? '#185D7A' : 'rgba(255,255,255,0.08)',
                              border: isSelected ? '2px solid #2596be' : '2px solid rgba(255,255,255,0.15)',
                              display: 'flex', alignItems: 'center', justifyContent: 'center',
                              fontSize: '11px', color: '#fff', fontWeight: 800,
                              transition: 'all 0.15s', flexShrink: 0,
                            }}>
                              {isSelected ? '✓' : ''}
                            </span>
                            <span style={{ fontFamily: 'monospace', fontSize: '11px', color: isSelected ? '#7dd3ee' : '#6b8ea0', display: 'block', marginBottom: '2px' }}>{sys.product_code}</span>
                            <span style={{ fontWeight: 600, fontSize: '13px', color: isSelected ? '#e8f4f8' : '#8ab8cc', wordBreak: 'break-word', display: 'block', paddingRight: '24px' }}>{sys.name}</span>
                            {sys.subcategory && <span style={{ fontSize: '11px', color: isSelected ? '#90c8de' : '#4a6b7a', display: 'block', marginTop: '2px' }}>{sys.subcategory}</span>}
                          </button>
                        )
                      })}
                    </div>
                  </div>
                )
              })}
              {editError && <p className="text-error text-sm">{editError}</p>}
            </div>
            <div className="px-6 py-4 border-t border-border flex items-center justify-between gap-3">
              <button onClick={() => setEditState(null)} className="text-sm text-text-faint hover:text-text-primary transition-colors">Cancel</button>
              <button onClick={saveEdit} disabled={editSaving || editSelectedIds.length === 0}
                className="px-6 py-2.5 bg-brand hover:bg-brand-hover disabled:opacity-50 text-white rounded-lg font-semibold text-sm transition-colors">
                {editSaving ? 'Saving…' : `Save ${editSelectedIds.length} product${editSelectedIds.length !== 1 ? 's' : ''}`}
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  )
}
