'use client'

import { useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase/client'

const NTW_MANUFACTURER_ID = 'a1000000-0000-0000-0000-000000000001'

type System = {
  id: string
  name: string
  product_code: string
  category: string
  subcategory: string | null
  sort_order: number
}

type EmbedWidgetSystem = {
  systems: {
    name: string
    product_code: string
  }
}

type EmbedWidget = {
  id: string
  public_token: string
  status: string
  embed_widget_systems: EmbedWidgetSystem[]
}

type Supplier = {
  id: string
  name: string
  suburb: string | null
  state: string | null
  website_url: string | null
  email: string | null
  phone: string | null
  embed_widgets: EmbedWidget[]
}

const AU_STATES = ['WA', 'VIC', 'NSW', 'QLD', 'SA', 'TAS', 'ACT', 'NT']

function slugify(name: string) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}

function buildEmbedCode(token: string, origin: string) {
  return `<iframe src="${origin}/widget/${token}" width="100%" height="720" frameborder="0" style="border:none;border-radius:12px;"></iframe>`
}

function CopyButton({ text, label = 'Copy' }: { text: string; label?: string }) {
  const [copied, setCopied] = useState(false)
  function handleCopy() {
    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }
  return (
    <button
      onClick={handleCopy}
      className="text-xs px-3 py-1.5 bg-brand hover:bg-brand-hover text-white rounded-lg font-medium transition-colors"
    >
      {copied ? 'Copied!' : label}
    </button>
  )
}

export default function SuppliersAdminPage() {
  const [suppliers, setSuppliers] = useState<Supplier[]>([])
  const [systems, setSystems] = useState<System[]>([])
  const [loading, setLoading] = useState(true)
  const [origin, setOrigin] = useState('')

  // Form state
  const [name, setName] = useState('')
  const [website, setWebsite] = useState('')
  const [email, setEmail] = useState('')
  const [phone, setPhone] = useState('')
  const [suburb, setSuburb] = useState('')
  const [stateVal, setStateVal] = useState('')
  const [selectedSystems, setSelectedSystems] = useState<string[]>([])

  // UI state
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [newWidget, setNewWidget] = useState<{ token: string; supplierName: string } | null>(null)

  useEffect(() => {
    setOrigin(window.location.origin)
    loadData()
  }, [])

  async function loadData() {
    setLoading(true)
    const [suppliersRes, systemsRes] = await Promise.all([
      supabase
        .from('suppliers')
        .select(`
          id, name, suburb, state, website_url, email, phone,
          embed_widgets (
            id, public_token, status,
            embed_widget_systems (
              systems ( name, product_code )
            )
          )
        `)
        .order('name'),
      supabase
        .from('systems')
        .select('id, name, product_code, category, subcategory, sort_order')
        .eq('manufacturer_id', NTW_MANUFACTURER_ID)
        .order('sort_order'),
    ])
    if (suppliersRes.data) setSuppliers(suppliersRes.data as unknown as Supplier[])
    if (systemsRes.data) setSystems(systemsRes.data)
    setLoading(false)
  }

  function toggleSystem(id: string) {
    setSelectedSystems(prev => {
      if (prev.includes(id)) return prev.filter(s => s !== id)
      if (prev.length >= 3) return prev
      return [...prev, id]
    })
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    if (!name.trim()) return setError('Business name is required')
    if (selectedSystems.length === 0) return setError('Select at least one product profile')

    setSubmitting(true)
    setError(null)
    setNewWidget(null)

    // 1. Insert supplier
    const { data: supplier, error: supplierErr } = await supabase
      .from('suppliers')
      .insert({
        name: name.trim(),
        slug: slugify(name),
        website_url: website.trim() || null,
        email: email.trim() || null,
        phone: phone.trim() || null,
        suburb: suburb.trim() || null,
        state: stateVal || null,
      })
      .select()
      .single()

    if (supplierErr || !supplier) {
      setError(supplierErr?.message || 'Failed to create supplier')
      setSubmitting(false)
      return
    }

    // 2. Insert embed_widget (public_token auto-generated by DB default)
    const { data: widget, error: widgetErr } = await supabase
      .from('embed_widgets')
      .insert({
        manufacturer_id: NTW_MANUFACTURER_ID,
        supplier_id: supplier.id,
        status: 'active',
      })
      .select()
      .single()

    if (widgetErr || !widget) {
      setError(widgetErr?.message || 'Failed to create widget')
      setSubmitting(false)
      return
    }

    // 3. Link selected systems to the widget
    const { error: systemsErr } = await supabase
      .from('embed_widget_systems')
      .insert(
        selectedSystems.map((systemId, i) => ({
          embed_widget_id: widget.id,
          system_id: systemId,
          sort_order: i,
        }))
      )

    if (systemsErr) {
      setError(systemsErr.message)
      setSubmitting(false)
      return
    }

    // Success — show the embed code
    setNewWidget({ token: widget.public_token, supplierName: name.trim() })
    setName('')
    setWebsite('')
    setEmail('')
    setPhone('')
    setSuburb('')
    setStateVal('')
    setSelectedSystems([])
    setSubmitting(false)
    loadData()
  }

  const CATEGORIES = ['Decking', 'Cladding', 'Screening & Fencing']

  if (loading) {
    return (
      <div className="min-h-screen bg-page flex items-center justify-center">
        <p className="text-text-faint">Loading...</p>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-page">

      {/* Nav bar */}
      <div className="sticky top-0 z-30 bg-surface border-b border-border px-6 py-4">
        <div className="max-w-5xl mx-auto flex items-center gap-3">
          <span className="text-sm font-semibold tracking-widest text-text-faint uppercase">
            BUILD<span className="text-brand">QUOTE</span>
          </span>
          <span className="text-text-faint text-sm">/</span>
          <span className="text-text-primary font-semibold text-sm">Supplier Admin</span>
        </div>
      </div>

      <div className="max-w-5xl mx-auto px-6 py-10 space-y-10">

        {/* Success panel */}
        {newWidget && (
          <div className="rounded-xl border border-success/40 bg-success/10 p-6">
            <p className="text-success font-bold text-base mb-1">
              Widget created for {newWidget.supplierName}
            </p>
            <p className="text-text-secondary text-sm mb-4">
              Send this embed code to the supplier — they paste it once into their website.
            </p>
            <div className="bg-page rounded-lg p-4 font-mono text-xs text-text-secondary break-all mb-4 leading-relaxed">
              {buildEmbedCode(newWidget.token, origin)}
            </div>
            <div className="flex flex-wrap gap-3">
              <CopyButton
                text={buildEmbedCode(newWidget.token, origin)}
                label="Copy embed code"
              />
              <a
                href={`/widget/${newWidget.token}`}
                target="_blank"
                rel="noopener noreferrer"
                className="text-xs px-3 py-1.5 bg-surface hover:bg-surface-hover border border-border text-text-secondary rounded-lg font-medium transition-colors"
              >
                Preview widget ↗
              </a>
              <button
                onClick={() => setNewWidget(null)}
                className="text-xs px-3 py-1.5 text-text-faint hover:text-text-primary transition-colors"
              >
                Dismiss
              </button>
            </div>
          </div>
        )}

        {/* Existing suppliers */}
        <section>
          <h2 className="text-lg font-bold text-text-primary mb-5">
            Active suppliers
            <span className="ml-2 text-sm font-normal text-text-faint">({suppliers.length})</span>
          </h2>

          {suppliers.length === 0 ? (
            <p className="text-text-faint text-sm">No suppliers yet — add the first one below.</p>
          ) : (
            <div className="space-y-4">
              {suppliers.map(supplier => (
                <div key={supplier.id} className="bg-surface border border-border rounded-xl p-5">
                  {/* Supplier header */}
                  <div className="flex flex-wrap items-baseline gap-x-4 gap-y-1 mb-4">
                    <span className="font-semibold text-text-primary">{supplier.name}</span>
                    {(supplier.suburb || supplier.state) && (
                      <span className="text-text-faint text-sm">
                        {[supplier.suburb, supplier.state].filter(Boolean).join(', ')}
                      </span>
                    )}
                    {supplier.email && (
                      <span className="text-text-faint text-sm">{supplier.email}</span>
                    )}
                    {supplier.phone && (
                      <span className="text-text-faint text-sm">{supplier.phone}</span>
                    )}
                    {supplier.website_url && (
                      <a
                        href={supplier.website_url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-brand text-sm hover:underline"
                      >
                        {supplier.website_url}
                      </a>
                    )}
                  </div>

                  {/* Each embed widget for this supplier */}
                  {supplier.embed_widgets.map(widget => {
                    const profiles = widget.embed_widget_systems.map(ews => ews.systems)
                    const code = buildEmbedCode(widget.public_token, origin)
                    return (
                      <div key={widget.id} className="bg-ui rounded-lg p-4">
                        {/* Profile chips */}
                        <div className="flex flex-wrap gap-2 mb-3">
                          {profiles.map((sys, i) => (
                            <span
                              key={i}
                              className="text-xs bg-brand-subtle text-brand-bright px-2.5 py-1 rounded-full font-medium"
                            >
                              {sys.product_code} — {sys.name}
                            </span>
                          ))}
                        </div>
                        {/* Embed code */}
                        <div className="font-mono text-xs text-text-faint bg-page rounded px-3 py-2.5 break-all mb-3 leading-relaxed">
                          {code}
                        </div>
                        <div className="flex gap-3">
                          <CopyButton text={code} label="Copy embed code" />
                          <a
                            href={`/widget/${widget.public_token}`}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="text-xs px-3 py-1.5 bg-surface hover:bg-surface-hover border border-border text-text-secondary rounded-lg font-medium transition-colors"
                          >
                            Preview ↗
                          </a>
                        </div>
                      </div>
                    )
                  })}
                </div>
              ))}
            </div>
          )}
        </section>

        {/* Add new supplier form */}
        <section className="bg-surface border border-border rounded-xl p-6">
          <h2 className="text-lg font-bold text-text-primary mb-2">Add new supplier</h2>
          <p className="text-text-faint text-sm mb-6">
            Fill in the supplier details, pick up to 3 product profiles they stock, then generate their widget embed code.
          </p>

          <form onSubmit={handleSubmit} className="space-y-6">

            {/* Supplier details */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="sm:col-span-2">
                <label className="block text-sm font-medium text-text-secondary mb-1.5">
                  Business name <span className="text-error">*</span>
                </label>
                <input
                  value={name}
                  onChange={e => setName(e.target.value)}
                  placeholder="e.g. Bunbury Timber & Hardware"
                  className="w-full bg-ui border border-border rounded-lg px-3 py-2 text-text-primary placeholder-text-faint text-sm focus:outline-none focus:border-brand"
                  required
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-text-secondary mb-1.5">Website</label>
                <input
                  value={website}
                  onChange={e => setWebsite(e.target.value)}
                  placeholder="https://example.com.au"
                  type="url"
                  className="w-full bg-ui border border-border rounded-lg px-3 py-2 text-text-primary placeholder-text-faint text-sm focus:outline-none focus:border-brand"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-text-secondary mb-1.5">Email</label>
                <input
                  value={email}
                  onChange={e => setEmail(e.target.value)}
                  placeholder="enquiries@example.com.au"
                  type="email"
                  className="w-full bg-ui border border-border rounded-lg px-3 py-2 text-text-primary placeholder-text-faint text-sm focus:outline-none focus:border-brand"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-text-secondary mb-1.5">Phone</label>
                <input
                  value={phone}
                  onChange={e => setPhone(e.target.value)}
                  placeholder="08 9999 0000"
                  type="tel"
                  className="w-full bg-ui border border-border rounded-lg px-3 py-2 text-text-primary placeholder-text-faint text-sm focus:outline-none focus:border-brand"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-text-secondary mb-1.5">Suburb</label>
                <input
                  value={suburb}
                  onChange={e => setSuburb(e.target.value)}
                  placeholder="Bunbury"
                  className="w-full bg-ui border border-border rounded-lg px-3 py-2 text-text-primary placeholder-text-faint text-sm focus:outline-none focus:border-brand"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-text-secondary mb-1.5">State</label>
                <select
                  value={stateVal}
                  onChange={e => setStateVal(e.target.value)}
                  className="w-full bg-ui border border-border rounded-lg px-3 py-2 text-text-primary text-sm focus:outline-none focus:border-brand"
                >
                  <option value="">Select state</option>
                  {AU_STATES.map(s => <option key={s} value={s}>{s}</option>)}
                </select>
              </div>
            </div>

            {/* Product profile selection */}
            <div>
              <label className="block text-sm font-medium text-text-secondary mb-1">
                Product profiles to display{' '}
                <span className="text-error">*</span>
                <span className="text-text-faint font-normal ml-1">(select up to 3)</span>
              </label>
              <p className="text-text-faint text-xs mb-3">
                These are the NTW profiles this supplier stocks and wants to showcase on their website.
              </p>

              {CATEGORIES.map(cat => {
                const catSystems = systems.filter(s => s.category === cat)
                if (catSystems.length === 0) return null
                return (
                  <div key={cat} className="mb-5">
                    <p className="text-xs font-semibold text-text-faint uppercase tracking-widest mb-2">
                      {cat}
                    </p>
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2">
                      {catSystems.map(sys => {
                        const isSelected = selectedSystems.includes(sys.id)
                        const isDisabled = !isSelected && selectedSystems.length >= 3
                        return (
                          <button
                            key={sys.id}
                            type="button"
                            onClick={() => toggleSystem(sys.id)}
                            disabled={isDisabled}
                            className={`text-left px-3 py-2.5 rounded-lg border text-sm transition-all ${
                              isSelected
                                ? 'bg-brand-subtle border-brand'
                                : isDisabled
                                ? 'bg-ui/30 border-border/30 cursor-not-allowed opacity-50'
                                : 'bg-ui border-border hover:border-brand/60'
                            }`}
                          >
                            <span className="font-mono text-xs text-text-faint block mb-0.5">
                              {sys.product_code}
                            </span>
                            <span className={`font-medium text-sm ${isSelected ? 'text-text-primary' : 'text-text-secondary'}`}>
                              {sys.name}
                            </span>
                            {sys.subcategory && (
                              <span className="text-text-faint text-xs block">{sys.subcategory}</span>
                            )}
                          </button>
                        )
                      })}
                    </div>
                  </div>
                )
              })}

              {selectedSystems.length > 0 && (
                <p className="text-brand text-xs mt-1 font-medium">
                  {selectedSystems.length} of 3 selected
                </p>
              )}
            </div>

            {/* Error */}
            {error && (
              <p className="text-error text-sm rounded-lg bg-error/10 border border-error/30 px-4 py-3">
                {error}
              </p>
            )}

            <button
              type="submit"
              disabled={submitting}
              className="px-6 py-3 bg-brand hover:bg-brand-hover disabled:opacity-50 disabled:cursor-not-allowed text-white rounded-lg font-semibold text-sm transition-colors"
            >
              {submitting ? 'Creating supplier...' : 'Create supplier & generate embed code →'}
            </button>
          </form>
        </section>

      </div>
    </div>
  )
}
